paytm.payment:
  config:
    merchantId: cGFGVj15445537403537
    merchantKey: Y72L97GK2Z6tGXcO
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Retail
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    callbackUrl: http://localhost:8071/pgresponse
    details:
      MID: ${paytm.payment.config.merchantid}
      CHANNEL_ID: WEB
      INDUSTRY_TYPE_ID: Retail
      WEBSITE: WEBSTAGING
      CALLBACK_URL: ${paytm.payment.config.callbackUrl}


